# sCoinEngine 配置

# 设置要从 'langs' 文件夹中使用的语言文件。
# 默认为 'en'（英文）。你也可以创建自己的语言文件（例如 'custom.yml'）。
language: en

# 数据库设置
# 目前仅支持 'SQLITE'。
database:
  type: SQLITE

# 排行榜（leaderboard）设置
baltop:
  # 每页显示多少名玩家
  entries-per-page: 10
  # 排行榜上每一行的格式（占位符位于你的语言文件中）
  format: "&e#%rank% &7- &a%player%&7: &f%formatted_balance%"

# 这是大多数插件消息中使用的前缀。
message-prefix: "&8[&6sCoinEngine&8] "

# 由 Saym 制作，感谢使用我们的插件