# CoreProtect 配置

# CoreProtect 是捐赠软件。请前往 coreprotect.net/donate/ 获取捐赠密钥。
donation-key: 

# MySQL 是可选的，并非必需。
# 如果你更倾向于使用 MySQL，请启用以下选项并填写相关字段。
use-mysql: false
table-prefix: co_
mysql-host: 127.0.0.1
mysql-port: 3306
mysql-database: database
mysql-username: root
mysql-password: 

# 修改此选项后，将自动尝试翻译语言短语。
# 语言代码列表：https://coreprotect.net/languages/
language: zh

# 启用后，CoreProtect 将在服务器启动时检查更新。
# 如果有可用更新，你将通过服务器控制台收到通知。
check-updates: true

# 自动将错误发送给插件作者。
error-reporting: true

# 启用后，其他插件将能够使用 CoreProtect API。
api-enabled: true

# 启用后，回滚和恢复期间将显示额外数据。
# 也可以在回滚命令中添加 "#verbose" 来手动触发。
verbose: true

# 如果回滚或恢复命令未指定半径，将使用此值作为半径。
# 设为 "0" 可禁用自动添加半径。
default-radius: 10

# 命令中可使用的最大半径。设为 "0" 可禁用。
# 若要在不指定半径的情况下执行回滚或恢复，可以使用 "r:#global"。
max-radius: 100

# 启用后，从容器等中取出的物品将包含在回滚中。
rollback-items: true

# 启用后，实体（例如被杀死的动物）将包含在回滚中。
rollback-entities: true

# 启用后，将不再记录通用数据，例如僵尸在白天燃烧。
skip-generic-data: true

# 记录玩家放置的方块。
block-place: true

# 记录玩家破坏的方块。
block-break: true

# 记录从其他方块上脱落的方块；例如，告示牌或火把
# 会在玩家破坏泥土方块时随之掉落。此选项对床/门的
# 正确回滚必不可少。
natural-break: true

# 正确追踪方块的移动，例如沙或砾石下落。
block-movement: true

# 正确追踪由活塞移动的方块。
pistons: true

# 记录在火灾中被烧毁的方块。
block-burn: true

# 记录方块自然燃烧的时刻，例如火势蔓延引发。
block-ignite: true

# 记录火焰自然熄灭的时刻。
fire-extinguish: false

# 记录爆炸，例如 TNT 和苦力怕。
explosions: true

# 记录实体改变方块的情况，例如末影人破坏方块。
entity-change: true

# 记录被击杀的实体，例如被杀的牛和末影人。
entity-kills: true

# 记录告示牌上的文字。若禁用，回滚后告示牌将为空白。
sign-text: true

# 记录使用桶的玩家放置/移除的岩浆和水的源方块。
buckets: true

# 记录树木叶子的自然凋零。
leaf-decay: true

# 记录树木生长。树木会与种植树苗的玩家关联。
tree-growth: true

# 记录蘑菇的生长。
mushroom-growth: true

# 记录藤蔓的自然生长。
vine-growth: true

# 记录由 sculk 催化物引发的 sculk 方块蔓延。
sculk-spread: true

# 记录传送门（如下界传送门）自然生成的情况。
portals: true

# 记录水的流动。如果水破坏了其他方块（如火把），
# 此选项可让这些破坏被正确回滚。
water-flow: true

# 记录岩浆的流动。如果岩浆破坏了其他方块（如火把），
# 此选项可让这些破坏被正确回滚。
lava-flow: true

# 允许液体被正确追踪并与玩家关联。
# 例如，如果玩家放置的水流动并破坏了火把，
# 只需回滚该玩家即可全部正确恢复。
liquid-tracking: true

# 记录物品交易，例如玩家从箱子、熔炉
# 或发射器中取出物品。
item-transactions: true

# 记录玩家丢弃的物品。
item-drops: true

# 记录玩家拾取的物品。
item-pickups: true

# 记录所有漏斗交易，例如漏斗从箱子、熔炉
# 或发射器中移走物品。
hopper-transactions: true

# 记录玩家交互，例如玩家开门、按下按钮或打开箱子。
# 玩家交互无法被回滚。
player-interactions: true

# 记录玩家在聊天中发送的消息。
player-messages: true

# 记录玩家使用的所有命令。
player-commands: true

# 记录玩家的登录和退出。
player-sessions: true

# 记录玩家更改 Minecraft 用户名的时刻。
username-changes: true

# 如果你的服务器使用了 "WorldEdit" 插件，将记录通过它所做的更改。
worldedit: true
