# PlaceholderAPI
# 版本：2.12.3
# 作者：extended_clip
# 贡献者：https://github.com/PlaceholderAPI/PlaceholderAPI/graphs/contributors
# 问题反馈：https://github.com/PlaceholderAPI/PlaceholderAPI/issues
# 扩展：https://placeholderapi.com/ecloud
# 维基：https://wiki.placeholderapi.com/
# Discord：https://helpch.at/discord
# 如果你在使用组件替换的插件时遇到性能问题，或者某些东西看起来不太对劲，
# 可以通过将 use_adventure_provided_replacer 改为 true，改用 adventure 自身提供的替换器
# 此插件默认不提供任何占位符。
# 下载占位符：/papi ecloud
check_updates: true
cloud_enabled: true
cloud_sorting: "name"
boolean:
  'true': 'yes'
  'false': 'no'
date_format: MM/dd/yy HH:mm:ss
detect_malicious_expansions: true
use_adventure_provided_replacer: false
debug: false
